---
- name: Roles Playbook
  hosts: all
  become: true
  become_method: sudo
  connection: ssh
  ignore_errors: false
  roles: 
    - {role: company_prerequsites}
    - {role: wordpress}
    - {role: VPC}
    - {role: 3 private subnets}
    - {role: 3 public subnets}
    - {role: IGW}
    - {role: EIP (if needed)} 
    - {role: Sec group}
    - {role: VGW if needed}
    - {role: route tables}